version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: mixtli
      POSTGRES_PASSWORD: mixtli
      POSTGRES_DB: mixtli
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    command: npm run dev
    restart: always
    environment:
      DATABASE_URL: postgresql://mixtli:mixtli@db:5432/mixtli
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: S3gura#123
      ADMIN_NAME: Admin
    depends_on:
      - db
    ports:
      - "10000:10000"

  swagger:
    image: swaggerapi/swagger-ui
    restart: always
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml:ro
    ports:
      - "8080:8080"

volumes:
  db_data:
