version: "3.9"
services:
  audit:
    build: ./services/audit-service
    ports: ["7004:7004"]
    volumes: ["./services/audit-service/data:/usr/src/app/data"]
  wfm:
    build: ./services/wfm-service
    ports: ["7001:7001"]
  scoring:
    build: ./services/scoring-service
    ports: ["7002:7002"]
  rules:
    build: ./services/rules-service
    ports: ["7003:7003"]
  gateway:
    build: ./services/api-gateway
    ports: ["7000:7000"]
    environment:
      - WFM_URL=http://wfm:7001
      - SCORING_URL=http://scoring:7002
      - RULES_URL=http://rules:7003
      - AUDIT_URL=http://audit:7004
    depends_on: [audit, wfm, scoring, rules]
