version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: mixtli_db
    environment:
      POSTGRES_USER: mixtli
      POSTGRES_PASSWORD: mixtli
      POSTGRES_DB: mixtli
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mixtli"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: mixtli_redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./apps/api
      dockerfile: ../../docker/Dockerfile.api
    container_name: mixtli_api
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      JWT_SECRET: ${JWT_SECRET}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM: ${SENDGRID_FROM}
      APP_ENV: ${APP_ENV}
      PORT: 8080
    ports:
      - "8080:8080"

  worker:
    build:
      context: ./apps/worker
      dockerfile: ../../docker/Dockerfile.worker
    container_name: mixtli_worker
    env_file:
      - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: ${DATABASE_URL}
      REDIS_URL: ${REDIS_URL}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
      SENDGRID_FROM: ${SENDGRID_FROM}

volumes:
  db_data:
