# Netlify proxy: /api/* -> tu backend. Quita CORS del navegador.
[build]
  publish = "."

[[redirects]]
  from = "/api/*"
  to   = "https://mixtli-pro.onrender.com/api/:splat"
  status = 200
  force  = true
