[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3", "@aws-sdk/s3-request-presigner"]

[[redirects]]
  from = "/api/health"
  to   = "/.netlify/functions/health"
  status = 200

[[redirects]]
  from = "/api/presign"
  to   = "/.netlify/functions/presign"
  status = 200
