services:
  - type: web
    name: mixtli-pro
    env: node
    plan: starter
    region: oregon
    buildCommand: "npm ci"
    startCommand: "node server.js"
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: ALLOWED_ORIGIN
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_REGION
        value: "auto"
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
