services:
  - type: web
    name: mixtli-full-backend
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: S3_BUCKET
        value: your-bucket-name
      - key: AWS_REGION
        value: auto
      - key: S3_ENDPOINT
        value: 
      - key: AWS_ACCESS_KEY_ID
        value: your-access-key
      - key: AWS_SECRET_ACCESS_KEY
        value: your-secret
      - key: ALLOWED_ORIGINS
        value: https://lovely-bienenstitch-6344a1.netlify.app,https://meek-alfajores-1c364d.netlify.app
      - key: SIGNED_URL_TTL
        value: "3600"
      - key: DEFAULT_PREFIX
        value: public/
