services:
  - type: web
    name: mixtli-pro
    env: node
    plan: free
    rootDir: backend
    buildCommand: "npm ci --omit=dev"
    startCommand: "node server.js"
    envVars:
      - key: R2_ACCESS_KEY_ID
        sync: false
      - key: R2_SECRET_ACCESS_KEY
        sync: false
      - key: R2_BUCKET
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: PUBLIC_BASE_URL
        sync: false
      - key: ALLOWED_ORIGINS
        value: "http://localhost:5173,https://*.netlify.app"
