services:
  - type: web
    name: mixtli-pro
    env: node
    plan: free
    buildCommand: |
      npm ci
      npx prisma generate
    startCommand: node server.js
    envVars:
      - key: DATABASE_URL
        sync: false