name: Validate Postman Collection

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check collection file exists
        run: test -f postman/mixtli-api-prod-smoke.postman_collection.json
