version: "3.9"

services:
  db:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    image: postgres:16-alpine
    container_name: mixtli_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mixtli}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mixtli}
      POSTGRES_DB: ${POSTGRES_DB:-mixtli}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [mixtli]

  adminer:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: adminer:4
    container_name: mixtli_adminer
    restart: unless-stopped
    environment:
      ADMINER_DEFAULT_SERVER: db
    ports:
      - "${ADMINER_PORT:-8080}:8080"
    depends_on: [db]
    networks: [mixtli]

  swagger:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: swaggerapi/swagger-ui:latest
    container_name: mixtli_swagger
    environment:
      SWAGGER_JSON: /openapi/openapi.yaml
    volumes:
      - ../openapi.yaml:/openapi/openapi.yaml:ro
    ports:
      - "${SWAGGER_PORT:-9000}:8080"
    networks: [mixtli]

  seed:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: node:18-alpine
    container_name: mixtli_seed
    working_dir: /app
    environment:
      DATABASE_URL: ${DATABASE_URL:-postgresql://mixtli:mixtli@db:5432/mixtli?schema=public}
      ADMIN_EMAIL: ${ADMIN_EMAIL:-admin@example.com}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD:-S3gura#123}
      ADMIN_NAME: ${ADMIN_NAME:-Admin}
      # optional: PRISMA_LOG_LEVEL: query
    volumes:
      - ..:/app
    command: sh -c "npm ci && npx prisma generate && npx prisma migrate deploy && npm run seed"
    depends_on:
      - db
    networks: [mixtli]

networks:
  mixtli:

volumes:
  db_data:


  app:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:10000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    build:
      context: ../app
    container_name: mixtli_app
    environment:
      PORT: ${APP_PORT:-10000}
      DATABASE_URL: ${DATABASE_URL:-postgresql://mixtli:mixtli@db:5432/mixtli?schema=public}
      JWT_SECRET: ${JWT_SECRET:-super-secret-change-me}
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:5173,http://localhost:9000,http://localhost:8080,http://localhost:3000}
    ports:
      - "${APP_PORT:-10000}:10000"
    depends_on:
      - db
    networks: [mixtli]

  web:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    build:
      context: ../web
    container_name: mixtli_web
    ports:
      - "${WEB_PORT:-5173}:80"
    depends_on:
      - app
    networks: [mixtli]


  caddy:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    image: caddy:2-alpine
    container_name: mixtli_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - web
      - swagger
      - adminer
    networks: [mixtli]

volumes:
  caddy_data:
  caddy_config:


  caddy:
    image: caddy:2-alpine
    container_name: mixtli_caddy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ACME_AGREE=true
      - EMAIL=${ACME_EMAIL}
      - DOMAIN_API=${DOMAIN_API}
      - DOMAIN_WEB=${DOMAIN_WEB}
      - DOMAIN_SWAGGER=${DOMAIN_SWAGGER}
      - DOMAIN_ADMINER=${DOMAIN_ADMINER}
      - ADMINER_USER=${ADMINER_USER:-}
      - ADMINER_PASS_BCRYPT=${ADMINER_PASS_BCRYPT:-}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
      - web
      - swagger
      - adminer
    networks: [mixtli]

volumes:
  caddy_data:
  caddy_config:


  webclient:
    build:
      context: ../webclient
    container_name: mixtli_webclient
    environment:
      - VITE_API_URL=${API_PUBLIC_URL:-http://localhost:10000}
      - VITE_CLIENT_ID=${OAUTH_CLIENT_ID:-mixtli-web}
      - VITE_REDIRECT_URI=${WEBCLIENT_REDIRECT_URI:-http://localhost:5174/callback}
    ports:
      - "${WEBCLIENT_PORT:-5174}:80"
    depends_on:
      - app
    networks: [mixtli]
