# fly api app config
app = "mixtli-api"         # cambia este nombre: flyctl apps create mixtli-api
primary_region = "dfw"     # cambia a la región deseada
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  dockerfile = "../../docker/Dockerfile.api"
  context = "../.."

[env]
  APP_ENV = "production"
  PORT = "8080"

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [[services.ports]]
    port = 80
  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 0

[checks]
  [checks.health]
    port = 8080
    type = "http"
    interval = "15s"
    timeout = "2s"
    method = "get"
    path = "/health"
