route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 3h
  receiver: default-receiver
  routes:
    - matchers:
        - severity="critical"
      receiver: critical-receiver

receivers:
  - name: default-receiver
    email_configs:
      - to: "REPLACE_ME@example.com"
        from: "REPLACE_ME@example.com"
        smarthost: "smtp.example.com:587"
        auth_username: "REPLACE_ME@example.com"
        auth_password: "REPLACE_ME_PASSWORD"
        require_tls: true

  - name: critical-receiver
    webhook_configs:
      - url: "http://REPLACE_ME-webhook.local/alert"
