#cloud-config
package_update: true
package_upgrade: true
packages:
  - docker.io
  - docker-compose
  - git
  - nginx
  - certbot
  - python3-certbot-nginx

write_files:
  - path: /etc/nginx/sites-available/mixtli.conf
    permissions: "0644"
    owner: root:root
    content: |
      server {
        listen 80;
        server_name ${domain};
        location / {
          proxy_pass http://127.0.0.1:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
      }

runcmd:
  - systemctl enable docker && systemctl start docker
  - rm -f /etc/nginx/sites-enabled/default || true
  - ln -s /etc/nginx/sites-available/mixtli.conf /etc/nginx/sites-enabled/mixtli.conf
  - systemctl restart nginx
  # Clonar repo si no existe (asume que subes este bundle a un repo)
  - mkdir -p /opt/mixtli && cd /opt/mixtli
  - if [ ! -d src ]; then echo "Sube el repo y clónalo manualmente en /opt/mixtli/src"; fi
  # Levantar stack sin Nginx en contenedor
  - if [ -d /opt/mixtli/src ]; then cd /opt/mixtli/src && docker compose -f docker-compose.prod.no-nginx.yml up -d --build; fi
  # Emitir/renovar certificados (requiere DNS apuntando a esta IP)
  - certbot --nginx -n --agree-tos -m ${admin_email} -d ${domain} || true
