[[redirects]]
  from = "/api/*"
  to = "https://mixtli-pro.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/files/*"
  to = "https://mixtli-pro.onrender.com/files/:splat"
  status = 200
  force = true

# SPA fallback (no afecta a /portada/ ni /biblioteca/ porque ya existen como carpetas)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
