global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['host.docker.internal:10000']  # Cambia el puerto si tu API corre en otro
